version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"    # RabbitMQ default port
      - "15672:15672"  # RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  code-processor:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
      - db
      - redis
      - prometheus
      - grafana
    privileged: true  
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  db:
    image: postgres:13.0
    environment:
      POSTGRES_DB: code-processor
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        target: /var/lib/postgresql/dataConfig
  test:
    image: python:3.10  
    working_dir: /app
    volumes:
      - .:/app  
    depends_on:
      - code-processor  
    command: >
      sh -c "pip install -r tests/requirements.txt && pytest tests/tests.py"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin