version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"    # RabbitMQ default port
      - "15672:15672"  # RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  code-processor:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
    privileged: true  
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  test:
    image: python:3.10  
    working_dir: /app
    volumes:
      - .:/app  
    depends_on:
      - code-processor  
    command: >
      sh -c "pip install -r tests/requirements.txt && pytest tests/tests.py"